export { Home_page } from "./home_page";
export { About_page } from "./about_page";
export { Services_page } from "./services_page";
export { Team_page } from "./team_page";
export { Club_cards } from "./club_cards";
export { Saunas_pools_page } from "./saunas_pools_page";
export { Kids_fitness_page } from "./kids_fitness_page";
export { Presentation_directions_page } from "./presentation_directions_page";
export { Current_direction_page } from "./current direction_page";
export { Person_team_page } from "./person_team_page";
export { Stock_presentation_page } from "./stock_presentation_page";
export { News_presentation_page } from "./news_presentation_page";
export { Cards_presentation_page } from "./cards_presentation_page";
export { Stock_page } from "./stock_page";
export { News_page } from "./news_page";
export { Register } from "./register";
export { Login } from "./login";
export { Personal_account_page } from "./personal_account_page";
export { Congratulations_registration } from "./congratulations_registration"