export const paths = {
  home: "/",
  about_club: "/about_club",
  services: "/services",
  team: "/team",
  club_cards: "/club_cards",
  pools: "/pool",
  kids_fitness: "/kids_fitnes",
  schedule: "/schedule",
  mind_body: "/services/mind-body",
  strength_functional_training: "/strength_functional_training",
  aerobics: "/services/aerobics",
  gym: "/services/gym",
  pool: "/services/pool",
  martial_arts: "/services/martial_arts",
  dance: "/services/dance",
  personal_training: "/services/personal_training",
  yoga: "services/yoga",
  inbody: "services/inbody",
  group_programs: "services/group_training",
};
